# Generated by Django 2.2.4 on 2019-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20190818_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='media/', verbose_name='Изображение', width_field=100),
        ),
    ]
